In [72]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [73]:
df=pd.read_excel('standardscaler1.xlsx')

In [74]:
df

     Feature1  Feature2      Feature3         Target
0           7    506815  78179.054805  147107.322662
1           4    293822  70538.588873  127684.231772
2           8     77218  44636.920014   87982.249559
3           5    588518  86421.631346  166046.587018
4           7    771044  55814.069145  101011.603738
..        ...       ...           ...            ...
995         8    318348  38587.511702   68752.511537
996         1    183958  79172.046754  144130.196824
997         9    990156  59598.924619  103252.136934
998         7    278707  10126.081336   22002.231220
999         3     93324  84713.964255  150272.089596

[1000 rows x 4 columns]

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Feature1  1000 non-null   int64
 1   Feature2  1000 non-null   int64
 2   Feature3  1000 non-null   float64
 3   Target    1000 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 31.4 KB

In [76]:
x=df.drop('Target',axis=1)
y=df['Target']

In [77]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [78]:
model=LinearRegression()

In [79]:
model.fit(xtrain,ytrain)

LinearRegression()

In [80]:
train_score=model.score(xtrain,ytrain)
train_score

0.9902808869604561

In [81]:
test_score=model.score(xtest,ytest)
test_score

0.9902822563064015

In [82]:
model.coef_

array([-1.90917070e+01,  2.55230384e-04,  1.79990677e+00])

**with Using StandardScalar()**

In [83]:
scaler=StandardScaler()

In [84]:
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.transform(xtest)
xtrain_scaled
xtest_scaled

array([[ 0.04029928,  1.20894202,  1.30817812],
       [ 1.59400657,  0.88435119,  0.91114696],
       [ 0.4287261 , -1.24831658,  0.53753872],
       [ 1.20557975,  0.90052814,  0.00295259],
       [-0.73655436, -0.75826634,  0.99043722],
       [-1.12498118,  1.20470035, -0.74078814],
       [-1.12498118, -0.29065208, -0.54749276],
       [ 1.59400657, -0.1559706 ,  0.57691668],
       [ 1.59400657, -1.55783743,  1.56383811],
       [ 0.4287261 , -1.78565622,  1.02825118],
       [-0.73655436, -1.68545292,  0.12557919],
       [ 1.20557975,  1.42494622, -0.69080137],
       [-1.513408  , -1.06572153,  0.16861156],
       [-1.513408  ,  0.63978299, -0.93518994],
       [-0.73655436,  0.62916159,  0.87745526],
       [ 0.04029928, -0.50244566, -0.75674424],
       [-1.513408  ,  0.80383197, -0.63243624],
       [ 0.04029928,  1.46721114,  0.43662534],
       [ 0.4287261 , -0.462474  , -1.61086096],
       [-1.12498118, -1.0698356 ,  0.67584916],
       [ 1.59400657, -1.23433978,  0.82124867],
       [-1.513408  ,  1.59901312,  0.4900836 ],
       [ 1.59400657,  0.90786657,  1.08183098],
       [-0.73655436, -1.63181483, -1.53577419],
       [-1.12498118, -1.64453292, -1.53738435],
       [-0.73655436,  0.61353985, -0.87502733],
       [ 0.04029928,  1.36093846, -0.86667353],
       [ 0.81715293,  1.18591978, -1.14516752],
       [ 1.59400657, -0.88013317,  1.11410863],
       [-1.513408  ,  0.33891446, -1.18431246],
       [-1.513408  ,  1.20026902, -0.59860239],
       [ 0.04029928,  0.17292052, -0.24883907],
       [ 0.04029928,  0.89720033, -0.00665398],
       [ 0.4287261 ,  0.46514365, -1.68039325],
       [ 0.4287261 , -1.03517464,  1.54556811],
       [-1.12498118,  0.96355308,  0.41805506],
       [-1.513408  ,  0.80420096, -1.07213519],
       [ 0.81715293,  0.29666333, -1.69424991],
       [-1.513408  , -0.61764997, -0.73340905],
       [ 1.20557975, -1.47304551,  0.37581129],
       [-0.34812754,  0.10348136,  0.78905703],
       [ 1.20557975,  1.25515892,  1.44657132],
       [ 1.59400657,  0.40632934, -0.68911959],
       [-0.73655436, -1.64607786, -0.38831854],
       [-1.12498118, -1.07611188, -0.75698468],
       [ 1.59400657, -0.15660168,  1.51059975],
       [ 1.59400657,  0.62644072,  0.76570413],
       [-0.73655436, -0.02693777,  1.20614021],
       [ 0.81715293,  0.55908101, -0.77069906],
       [-1.513408  ,  0.88228898, -0.79152218],
       [ 0.4287261 , -0.06493688, -1.52423806],
       [-0.73655436,  0.19811532, -0.89164549],
       [-0.73655436,  1.15423488,  0.01644454],
       [-1.513408  , -1.00113787,  0.72570636],
       [-1.513408  ,  1.30290352,  1.65035342],
       [-0.73655436,  0.42595825, -1.25911725],
       [ 1.59400657,  1.51561784, -0.35643896],
       [ 1.20557975, -0.6471692 , -1.53960714],
       [ 1.20557975,  0.32404794, -1.12837786],
       [ 0.04029928, -0.39734893, -0.73594972],
       [ 0.4287261 ,  0.1298521 ,  0.33889457],
       [-0.34812754, -1.49704368,  1.14399402],
       [ 1.20557975,  0.32574805, -1.29490784],
       [-1.513408  , -1.71637224, -1.05966629],
       [-1.513408  , -0.31479854,  1.2348761 ],
       [ 1.20557975, -0.31867121, -0.63720902],
       [ 1.20557975,  0.64356946,  1.30081507],
       [-1.12498118,  0.96711883,  1.0052044 ],
       [ 1.59400657,  1.57924972, -0.20159931],
       [ 0.04029928, -0.37956152,  0.82779122],
       [ 1.59400657, -1.08313649,  0.08596696],
       [-0.34812754, -0.05513967, -0.419407  ],
       [-0.73655436,  0.63274459, -0.08427615],
       [ 0.04029928,  1.19895169, -0.63128301],
       [-0.73655436, -1.49132605, -0.91347493],
       [-1.12498118, -0.94057172, -1.29703648],
       [-1.12498118, -0.29119005, -0.12546853],
       [ 1.59400657, -0.84106502,  1.616595  ],
       [ 0.4287261 , -0.05525002,  1.47560618],
       [-0.73655436, -1.4759526 , -1.05461999],
       [-1.513408  , -0.97837082, -0.36585401],
       [ 1.20557975,  0.46406771, -1.34083964],
       [ 0.4287261 , -0.61854313,  1.59573965],
       [ 1.59400657, -1.13041899,  0.53353562],
       [ 0.81715293,  1.1698118 , -1.10314469],
       [ 0.04029928,  0.32374102,  0.93540266],
       [ 0.81715293, -0.84268237, -1.36801596],
       [ 1.59400657, -0.01282648, -1.31129305],
       [ 0.04029928, -0.79259624, -1.05642733],
       [-1.513408  ,  0.72012979,  1.21731043],
       [ 0.4287261 ,  0.23995951,  1.36055395],
       [ 0.4287261 ,  0.83960335, -0.95324722],
       [ 0.4287261 , -1.56146526,  0.04745336],
       [-0.73655436,  0.31432659,  1.61077492],
       [ 1.20557975,  0.73919659, -1.71793329],
       [-1.513408  ,  1.45568622,  0.1858749 ],
       [ 0.4287261 , -0.95478992, -0.6283098 ],
       [ 1.20557975,  0.55803956,  0.31386707],
       [ 0.04029928,  0.05798864,  0.88637702],
       [-1.12498118, -1.18916087, -1.49531183],
       [-0.34812754,  0.95144192, -0.61187448],
       [ 0.04029928, -1.17568066, -1.57098611],
       [-1.12498118, -1.12054246, -0.31907663],
       [ 0.4287261 ,  1.33490223, -1.15854545],
       [ 0.4287261 ,  1.24881367,  0.64862356],
       [-1.513408  , -0.05707428, -0.93564713],
       [-1.513408  , -1.54027763, -1.10146185],
       [ 0.4287261 ,  0.77744399, -0.33594034],
       [ 0.04029928, -1.76226499, -0.08139733],
       [ 0.4287261 ,  1.01313573,  0.61695853],
       [-0.34812754,  0.17907266, -0.03394716],
       [-0.34812754, -1.45297519, -0.93493933],
       [ 0.81715293,  0.85257664,  0.05289462],
       [ 1.59400657,  1.45432061, -1.48198399],
       [ 0.81715293,  1.49332324, -0.17997135],
       [-1.513408  , -1.77395198, -1.33495989],
       [ 0.4287261 , -0.21227094,  0.78974731],
       [-1.513408  , -1.10261367, -1.37627751],
       [ 0.04029928, -1.5305149 , -1.20273704],
       [ 1.20557975,  1.09227554,  0.97049118],
       [ 1.59400657, -0.27913752,  1.20314613],
       [ 0.04029928,  1.0723604 , -1.32405895],
       [ 0.4287261 , -1.63539093,  1.24797768],
       [ 0.4287261 ,  0.11011284, -0.36476554],
       [-1.12498118, -0.44318305, -1.39685773],
       [-1.12498118, -1.23811934,  1.57147002],
       [ 0.04029928,  0.71000152,  0.98257186],
       [-0.73655436, -0.18309656,  0.60604289],
       [ 0.04029928,  0.91393939,  1.64228144],
       [ 0.4287261 ,  1.15866277,  1.62662318],
       [ 1.59400657,  1.62891858, -0.43343815],
       [-0.73655436, -1.51348961,  1.59055206],
       [ 0.04029928, -0.70228326,  0.6159059 ],
       [ 1.20557975, -0.70598006, -0.38265845],
       [ 1.59400657, -1.54326059,  0.35647574],
       [ 0.4287261 ,  0.75455279,  0.59052095],
       [-1.12498118,  1.50143758,  0.09237385],
       [ 1.59400657,  0.7189366 , -0.56374221],
       [ 0.81715293, -1.75837163, -0.83844057],
       [ 1.59400657, -1.38421194,  1.32074091],
       [ 1.20557975, -1.22344939, -1.65794385],
       [ 0.04029928, -0.2000046 , -0.53568224],
       [-1.12498118, -0.8663081 , -0.60029603],
       [ 0.04029928, -0.42111604,  0.38071713],
       [-1.513408  ,  1.63381546, -0.73221215],
       [ 0.81715293, -0.46640185,  1.33586118],
       [-0.73655436, -1.25864142,  0.45642293],
       [-1.513408  ,  0.24200448, -1.50009724],
       [-0.73655436,  0.09326688, -1.46155796],
       [ 0.81715293,  1.61898343,  0.47356546],
       [ 1.20557975, -0.23555872,  0.40332177],
       [-1.513408  ,  1.63477415,  0.81550937],
       [ 0.4287261 , -0.63299928,  0.91034589],
       [ 1.59400657,  0.11265439,  0.41578375],
       [ 1.59400657,  0.22947605,  0.5194742 ],
       [ 0.04029928,  0.31388518, -1.34487614],
       [ 1.59400657, -0.74273081, -0.04085772],
       [ 1.20557975, -0.96108344, -0.16894987],
       [ 0.81715293,  1.26640796, -0.61725897],
       [-0.34812754, -0.00718817, -0.09229665],
       [ 0.04029928,  0.94296203, -0.76402229],
       [-1.12498118,  0.33990763, -1.13996172],
       [-1.12498118, -0.82033948, -0.97046384],
       [ 0.4287261 ,  0.19018375, -1.38081666],
       [ 0.4287261 ,  1.27499819, -0.90782105],
       [-0.73655436,  0.93106123,  0.56510186],
       [-1.12498118, -0.24732848,  1.31455776],
       [-1.513408  ,  1.49933054, -0.48376331],
       [-0.34812754,  0.55395652, -1.12773108],
       [ 1.20557975,  1.10001744,  0.89269802],
       [ 0.04029928,  0.12467244,  0.53768665],
       [-1.513408  , -1.33465688, -1.16171684],
       [-1.513408  , -0.63932729,  1.38590803],
       [-1.12498118, -1.06386968,  0.91919424],
       [ 0.04029928,  0.47007156,  1.32740654],
       [ 0.81715293,  0.11943071,  0.40741101],
       [-1.513408  , -0.03507625,  1.54403052],
       [ 0.4287261 , -1.67055192,  0.24294177],
       [-0.73655436,  0.81963304,  0.73148566],
       [ 1.59400657,  0.09880173, -0.52879724],
       [-1.513408  ,  1.3082556 ,  0.14642013],
       [ 0.04029928,  0.9559974 , -0.83404801],
       [ 0.81715293, -1.37707353,  1.13808534],
       [-0.73655436, -1.12896027,  0.71505851],
       [ 0.81715293,  0.38730392,  0.09983474],
       [ 1.20557975,  0.79251742, -1.07731047],
       [-1.513408  , -1.30464107,  0.01014645],
       [ 0.4287261 ,  0.65145964, -0.36008842],
       [ 0.81715293, -1.19329219,  1.35587374],
       [ 0.81715293, -1.57865952,  0.77091567],
       [-1.513408  ,  0.34670119, -1.12363294],
       [ 0.81715293, -0.85616603, -0.57468772],
       [ 0.81715293, -0.77994366, -1.33105479],
       [ 1.20557975,  1.48474335, -0.18692845],
       [ 0.04029928,  0.30465008,  1.72784419],
       [-1.12498118, -0.6730468 , -1.43255687],
       [-1.513408  ,  1.15080017, -0.49219254],
       [-0.34812754, -0.85031392, -0.13690591],
       [-1.12498118, -0.80295555,  0.81720809],
       [-1.513408  ,  1.52108028, -0.58170457]])

In [85]:
model.fit(xtrain_scaled,ytrain)

LinearRegression()

In [86]:
train_score=model.score(xtrain_scaled,ytrain)
train_score

0.9902808869604561

In [87]:
test_score=model.score(xtest_scaled,ytest)
test_score

0.9902822563064015

In [88]:
model.coef_

array([-4.91513611e+01,  7.40118263e+01,  5.19891719e+04])

**Using Robust scaler**

In [89]:
from sklearn.preprocessing import RobustScaler,MinMaxScaler

In [90]:
scaler=RobustScaler()

In [91]:
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.transform(xtest)
xtrain_scaled
xtest_scaled

array([[ 0.        ,  0.69172071,  0.71254131],
       [ 1.        ,  0.50357551,  0.48955076],
       [ 0.25      , -0.73259994,  0.27971557],
       [ 0.75      ,  0.51295229, -0.02053205],
       [-0.5       , -0.44854816,  0.53408373],
       [-0.75      ,  0.68926208, -0.43825029],
       [-0.75      , -0.17750113, -0.32968691],
       [ 1.        , -0.09943461,  0.301832  ],
       [ 1.        , -0.91201001,  0.85613146],
       [ 0.25      , -1.04406246,  0.55532175],
       [-0.5       , -0.98598081,  0.04834057],
       [ 0.75      ,  0.81692497, -0.41017547],
       [-1.        , -0.62676089,  0.07250948],
       [-1.        ,  0.36181447, -0.54743508],
       [-0.5       ,  0.3556579 ,  0.47062798],
       [ 0.        , -0.30026475, -0.44721196],
       [-1.        ,  0.4569035 , -0.37739499],
       [ 0.        ,  0.84142333,  0.22303807],
       [ 0.25      , -0.27709566, -0.92692232],
       [-0.75      , -0.62914557,  0.35739693],
       [ 1.        , -0.72449845,  0.43905984],
       [-1.        ,  0.91782077,  0.25306264],
       [ 1.        ,  0.51720592,  0.58541458],
       [-0.5       , -0.95489013, -0.88475021],
       [-0.75      , -0.96226202, -0.88565455],
       [-0.5       ,  0.34660294, -0.51364506],
       [ 0.        ,  0.77982364, -0.50895319],
       [ 0.5       ,  0.67837614, -0.66536794],
       [ 1.        , -0.51918681,  0.60354316],
       [-1.        ,  0.18741961, -0.6873535 ],
       [-1.        ,  0.68669351, -0.35839238],
       [ 0.        ,  0.0912032 , -0.16194957],
       [ 0.        ,  0.51102336, -0.02592753],
       [ 0.25      ,  0.26058685, -0.96597478],
       [ 0.25      , -0.60905476,  0.84587021],
       [-0.75      ,  0.54948394,  0.21260817],
       [-1.        ,  0.45711739, -0.6243497 ],
       [ 0.5       ,  0.16292925, -0.9737573 ],
       [-1.        , -0.36704156, -0.43410587],
       [ 0.75      , -0.86286139,  0.18888217],
       [-0.25      ,  0.05095362,  0.42097956],
       [ 0.75      ,  0.71850979,  0.79026916],
       [ 1.        ,  0.22649584, -0.40923091],
       [-0.5       , -0.96315752, -0.24028751],
       [-0.75      , -0.63278354, -0.447347  ],
       [ 1.        , -0.09980041,  0.8262304 ],
       [ 1.        ,  0.35408078,  0.40786353],
       [-0.5       , -0.02464227,  0.65523224],
       [ 0.5       ,  0.31503652, -0.45504961],
       [-1.        ,  0.50238017, -0.46674481],
       [ 0.25      , -0.04666801, -0.878271  ],
       [-0.5       ,  0.10580707, -0.52297856],
       [-0.5       ,  0.66001037, -0.01295436],
       [-1.        , -0.58932575,  0.38539897],
       [-1.        ,  0.74618438,  0.90472235],
       [-0.5       ,  0.2378735 , -0.72936723],
       [ 1.        ,  0.8694817 , -0.2223825 ],
       [ 0.75      , -0.38415203, -0.88690297],
       [ 0.75      ,  0.17880241, -0.65593811],
       [ 0.        , -0.23934668, -0.43553281],
       [ 0.25      ,  0.0662391 ,  0.16814808],
       [-0.25      , -0.87677164,  0.62032814],
       [ 0.75      ,  0.17978786, -0.74946884],
       [-1.        , -1.00390283, -0.6173466 ],
       [-1.        , -0.19149734,  0.6713716 ],
       [ 0.75      , -0.19374209, -0.3800756 ],
       [ 0.75      ,  0.36400925,  0.7084059 ],
       [-0.75      ,  0.55155079,  0.54237765],
       [ 1.        ,  0.90636515, -0.13541759],
       [ 0.        , -0.22903643,  0.44273443],
       [ 1.        , -0.63685527,  0.02609256],
       [-0.25      , -0.04098917, -0.25774819],
       [-0.5       ,  0.35773474, -0.06952363],
       [ 0.        ,  0.68592994, -0.37674729],
       [-0.5       , -0.87345748, -0.53523896],
       [-0.75      , -0.5542193 , -0.75066438],
       [-0.75      , -0.17781296, -0.09265912],
       [ 1.        , -0.49654143,  0.88576211],
       [ 0.25      , -0.04105313,  0.80657644],
       [-0.5       , -0.86454645, -0.61451237],
       [-1.        , -0.5761291 , -0.22767042],
       [ 0.75      ,  0.2599632 , -0.7752662 ],
       [ 0.25      , -0.36755927,  0.8740488 ],
       [ 1.        , -0.66426201,  0.27746725],
       [ 0.5       ,  0.66903935, -0.64176603],
       [ 0.        ,  0.17862451,  0.50317385],
       [ 0.5       , -0.4974789 , -0.79052965],
       [ 1.        , -0.01646283, -0.75867151],
       [ 0.        , -0.46844707, -0.61552745],
       [-1.        ,  0.40838653,  0.66150593],
       [ 0.25      ,  0.13006156,  0.74195794],
       [ 0.25      ,  0.47763796, -0.55757686],
       [ 0.25      , -0.91411284,  0.00446159],
       [-0.5       ,  0.17316755,  0.88249329],
       [ 0.75      ,  0.41943837, -0.98705896],
       [-1.        ,  0.83474305,  0.08220535],
       [ 0.25      , -0.56246071, -0.3750774 ],
       [ 0.75      ,  0.31443286,  0.15409151],
       [ 0.        ,  0.02458431,  0.47563885],
       [-0.75      , -0.69831104, -0.86202473],
       [-0.25      ,  0.54246385, -0.36584658],
       [ 0.        , -0.69049739, -0.90452681],
       [-0.75      , -0.65853719, -0.20139814],
       [ 0.25      ,  0.76473204, -0.67288159],
       [ 0.25      ,  0.71483184,  0.34210581],
       [-1.        , -0.04211054, -0.54769186],
       [-1.        , -0.90183168, -0.64082087],
       [ 0.25      ,  0.44160802, -0.21086956],
       [ 0.        , -1.03050401, -0.06790675],
       [ 0.25      ,  0.57822393,  0.32432131],
       [-0.25      ,  0.09476921, -0.0412566 ],
       [-0.25      , -0.85122787, -0.54729433],
       [ 0.5       ,  0.48515777,  0.00751764],
       [ 1.        ,  0.83395149, -0.85453922],
       [ 0.5       ,  0.8565589 , -0.12327036],
       [-1.        , -1.03727824, -0.77196387],
       [ 0.25      , -0.13206844,  0.42136725],
       [-1.        , -0.64814498, -0.7951697 ],
       [ 0.        , -0.89617283, -0.69770157],
       [ 0.75      ,  0.62409638,  0.52288114],
       [ 1.        , -0.17082685,  0.65355062],
       [ 0.        ,  0.61255281, -0.76584141],
       [ 0.25      , -0.95696297,  0.67873004],
       [ 0.25      ,  0.05479748, -0.22705909],
       [-0.75      , -0.26591389, -0.80672848],
       [-0.75      , -0.72668923,  0.86041789],
       [ 0.        ,  0.4025158 ,  0.5296662 ],
       [-0.5       , -0.11515786,  0.31819059],
       [ 0.        ,  0.52072596,  0.90018877],
       [ 0.25      ,  0.66257694,  0.89139438],
       [ 1.        ,  0.93515512, -0.26562871],
       [-0.5       , -0.88630433,  0.87113522],
       [ 0.        , -0.41609823,  0.3237301 ],
       [ 0.75      , -0.41824104, -0.23710855],
       [ 1.        , -0.90356072,  0.17802245],
       [ 0.25      ,  0.42833941,  0.30947277],
       [-0.75      ,  0.86126228,  0.02969095],
       [ 1.        ,  0.40769491, -0.33881333],
       [ 0.5       , -1.02824727, -0.49309629],
       [ 1.        , -0.81137007,  0.71959715],
       [ 0.75      , -0.71818597, -0.95336619],
       [ 0.        , -0.1249584 , -0.32305359],
       [-0.75      , -0.51117328, -0.3593436 ],
       [ 0.        , -0.25312301,  0.19163751],
       [-1.        ,  0.93799354, -0.43343363],
       [ 0.5       , -0.27937239,  0.72808936],
       [-0.5       , -0.73858461,  0.23415729],
       [-1.        ,  0.1312469 , -0.86471243],
       [-0.5       ,  0.04503292, -0.84306704],
       [ 0.5       ,  0.92939633,  0.24378531],
       [ 0.75      , -0.14556692,  0.20433329],
       [-1.        ,  0.93854923,  0.43583639],
       [ 0.25      , -0.3759386 ,  0.48910084],
       [ 1.        ,  0.05627066,  0.2113325 ],
       [ 1.        ,  0.12398494,  0.26956972],
       [ 0.        ,  0.17291169, -0.77753328],
       [ 1.        , -0.43954317, -0.04513789],
       [ 0.75      , -0.56610868, -0.1170802 ],
       [ 0.5       ,  0.72503016, -0.36887076],
       [-0.25      , -0.01319465, -0.0740283 ],
       [ 0.        ,  0.53754859, -0.45129963],
       [-0.75      ,  0.18799529, -0.66244413],
       [-0.75      , -0.48452812, -0.5672465 ],
       [ 0.25      ,  0.10120963, -0.7977191 ],
       [ 0.25      ,  0.73000938, -0.53206349],
       [-0.5       ,  0.53065043,  0.29519627],
       [-0.75      , -0.15238912,  0.71612441],
       [-1.        ,  0.86004096, -0.29389358],
       [-0.25      ,  0.31206618, -0.65557485],
       [ 0.75      ,  0.62858388,  0.479189  ],
       [ 0.        ,  0.06323678,  0.27979865],
       [-1.        , -0.78264607, -0.67466278],
       [-1.        , -0.37960656,  0.75619793],
       [-0.75      , -0.62568749,  0.49407048],
       [ 0.        ,  0.26344326,  0.72334086],
       [ 0.5       ,  0.06019847,  0.20662999],
       [-1.        , -0.02935965,  0.84500663],
       [ 0.25      , -0.97734362,  0.11425667],
       [-0.5       ,  0.4660624 ,  0.38864489],
       [ 1.        ,  0.04824113, -0.31918667],
       [-1.        ,  0.74928665,  0.06004578],
       [ 0.        ,  0.54510438, -0.49062923],
       [ 0.5       , -0.80723237,  0.61700956],
       [-0.5       , -0.66341648,  0.37941866],
       [ 0.5       ,  0.21546798,  0.03388133],
       [ 0.75      ,  0.45034516, -0.62725637],
       [-1.        , -0.76524776, -0.01649165],
       [ 0.25      ,  0.3685827 , -0.2244322 ],
       [ 0.5       , -0.70070571,  0.73932932],
       [ 0.5       , -0.92407929,  0.41079056],
       [-1.        ,  0.19193309, -0.65327315],
       [ 0.5       , -0.50529455, -0.34496083],
       [ 0.5       , -0.46111316, -0.76977059],
       [ 0.75      ,  0.85158567, -0.12717778],
       [ 0.        ,  0.16755867,  0.94824466],
       [-0.75      , -0.39915167, -0.82677872],
       [-1.        ,  0.65801948, -0.29862782],
       [-0.25      , -0.50190244, -0.09908287],
       [-0.75      , -0.47445173,  0.43679046],
       [-1.        ,  0.87264794, -0.34890181]])

In [92]:
model.fit(xtrain_scaled,ytrain)

LinearRegression()

In [93]:
train_score=model.score(xtrain_scaled,ytrain)
train_score

0.9902808869604561

In [94]:
test_score=model.score(xtest_scaled,ytest)
test_score

0.9902822563064014

In [95]:
model.coef_

array([-7.63668279e+01,  1.27686274e+02,  9.25658986e+04])

**Using MinMaxScaler**

In [96]:
scaler=MinMaxScaler()

In [97]:
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.transform(xtest)
xtrain_scaled
xtest_scaled

array([[ 5.00000000e-01,  8.72750347e-01,  8.76783323e-01],
       [ 1.00000000e+00,  7.77944643e-01,  7.61728835e-01],
       [ 6.25000000e-01,  1.55040189e-01,  6.53462006e-01],
       [ 8.75000000e-01,  7.82669567e-01,  4.98545866e-01],
       [ 2.50000000e-01,  2.98172881e-01,  7.84706126e-01],
       [ 1.25000000e-01,  8.71511452e-01,  2.83019437e-01],
       [ 1.25000000e-01,  4.34752523e-01,  3.39033934e-01],
       [ 1.00000000e+00,  4.74089966e-01,  6.64873228e-01],
       [ 1.00000000e+00,  6.46360871e-02,  9.50870278e-01],
       [ 6.25000000e-01, -1.90467557e-03,  7.95664121e-01],
       [ 2.50000000e-01,  2.73624625e-02,  5.34081468e-01],
       [ 8.75000000e-01,  9.35840334e-01,  2.97504953e-01],
       [ 0.00000000e+00,  2.08372112e-01,  5.46551692e-01],
       [ 0.00000000e+00,  7.06511754e-01,  2.26684312e-01],
       [ 2.50000000e-01,  7.03409480e-01,  7.51965416e-01],
       [ 5.00000000e-01,  3.72892367e-01,  2.78395563e-01],
       [ 0.00000000e+00,  7.54426784e-01,  3.14418412e-01],
       [ 5.00000000e-01,  9.48184968e-01,  6.24218615e-01],
       [ 6.25000000e-01,  3.84567192e-01,  3.08835998e-02],
       [ 1.25000000e-01,  2.07170484e-01,  6.93542579e-01],
       [ 1.00000000e+00,  1.59122500e-01,  7.35677475e-01],
       [ 0.00000000e+00,  9.86681372e-01,  6.39710127e-01],
       [ 1.00000000e+00,  7.84812957e-01,  8.11190854e-01],
       [ 2.50000000e-01,  4.30289478e-02,  5.26427723e-02],
       [ 1.25000000e-01,  3.93142765e-02,  5.21761691e-02],
       [ 2.50000000e-01,  6.98846719e-01,  2.44118657e-01],
       [ 5.00000000e-01,  9.17145102e-01,  2.46539478e-01],
       [ 7.50000000e-01,  8.66026067e-01,  1.65835528e-01],
       [ 1.00000000e+00,  2.62578312e-01,  8.20544501e-01],
       [ 0.00000000e+00,  6.18634798e-01,  1.54491829e-01],
       [ 0.00000000e+00,  8.70217159e-01,  3.24223024e-01],
       [ 5.00000000e-01,  5.70151689e-01,  4.25579905e-01],
       [ 5.00000000e-01,  7.81697589e-01,  4.95762008e-01],
       [ 6.25000000e-01,  6.55503515e-01,  1.07340405e-02],
       [ 6.25000000e-01,  2.17294172e-01,  9.45575869e-01],
       [ 1.25000000e-01,  8.01077738e-01,  6.18837189e-01],
       [ 0.00000000e+00,  7.54534558e-01,  1.86999351e-01],
       [ 7.50000000e-01,  6.06294192e-01,  6.71856224e-03],
       [ 0.00000000e+00,  3.39243770e-01,  2.85157799e-01],
       [ 8.75000000e-01,  8.94019057e-02,  6.06595490e-01],
       [ 3.75000000e-01,  5.49870067e-01,  7.26348756e-01],
       [ 8.75000000e-01,  8.86249270e-01,  9.16887883e-01],
       [ 1.00000000e+00,  6.38325175e-01,  2.97992313e-01],
       [ 2.50000000e-01,  3.88630366e-02,  3.85160561e-01],
       [ 1.25000000e-01,  2.05337322e-01,  2.78325887e-01],
       [ 1.00000000e+00,  4.73905643e-01,  9.35442491e-01],
       [ 1.00000000e+00,  7.02614774e-01,  7.19581388e-01],
       [ 2.50000000e-01,  5.11777563e-01,  8.47214060e-01],
       [ 7.50000000e-01,  6.82940513e-01,  2.74351637e-01],
       [ 0.00000000e+00,  7.77342318e-01,  2.68317368e-01],
       [ 6.25000000e-01,  5.00678874e-01,  5.59857946e-02],
       [ 2.50000000e-01,  5.77510526e-01,  2.39302930e-01],
       [ 2.50000000e-01,  8.56771620e-01,  5.02455659e-01],
       [ 0.00000000e+00,  2.27235551e-01,  7.07990550e-01],
       [ 0.00000000e+00,  9.00194396e-01,  9.75941296e-01],
       [ 2.50000000e-01,  6.44058339e-01,  1.32814372e-01],
       [ 1.00000000e+00,  9.62323483e-01,  3.94398852e-01],
       [ 8.75000000e-01,  3.30621865e-01,  5.15320343e-02],
       [ 8.75000000e-01,  6.14292621e-01,  1.70700953e-01],
       [ 5.00000000e-01,  4.03588767e-01,  2.84421548e-01],
       [ 6.25000000e-01,  5.57572370e-01,  5.95897503e-01],
       [ 3.75000000e-01,  8.23925787e-02,  8.29204900e-01],
       [ 8.75000000e-01,  6.14789186e-01,  1.22442723e-01],
       [ 0.00000000e+00,  1.83316210e-02,  1.90612677e-01],
       [ 0.00000000e+00,  4.27699885e-01,  8.55541347e-01],
       [ 8.75000000e-01,  4.26568764e-01,  3.13035322e-01],
       [ 8.75000000e-01,  7.07617695e-01,  8.74649609e-01],
       [ 1.25000000e-01,  8.02119216e-01,  7.88985463e-01],
       [ 1.00000000e+00,  9.80908926e-01,  4.39269376e-01],
       [ 5.00000000e-01,  4.08784070e-01,  7.37573422e-01],
       [ 1.00000000e+00,  2.03285591e-01,  5.22602357e-01],
       [ 3.75000000e-01,  5.03540420e-01,  3.76151527e-01],
       [ 2.50000000e-01,  7.04455994e-01,  4.73268108e-01],
       [ 5.00000000e-01,  8.69832397e-01,  3.14752604e-01],
       [ 2.50000000e-01,  8.40625692e-02,  2.32977041e-01],
       [ 1.25000000e-01,  2.44925566e-01,  1.21825869e-01],
       [ 1.25000000e-01,  4.34595395e-01,  4.61331091e-01],
       [ 1.00000000e+00,  2.73989243e-01,  9.66158544e-01],
       [ 6.25000000e-01,  5.03508189e-01,  9.25301807e-01],
       [ 2.50000000e-01,  8.85528092e-02,  1.92075029e-01],
       [ 0.00000000e+00,  2.33885296e-01,  3.91670492e-01],
       [ 8.75000000e-01,  6.55189259e-01,  1.09132280e-01],
       [ 6.25000000e-01,  3.38982897e-01,  9.60114931e-01],
       [ 1.00000000e+00,  1.89475434e-01,  6.52301960e-01],
       [ 7.50000000e-01,  8.61321287e-01,  1.78013199e-01],
       [ 5.00000000e-01,  6.14202977e-01,  7.68757824e-01],
       [ 7.50000000e-01,  2.73516851e-01,  1.01256934e-01],
       [ 1.00000000e+00,  5.15899156e-01,  1.17694501e-01],
       [ 5.00000000e-01,  2.88145887e-01,  1.91551287e-01],
       [ 0.00000000e+00,  7.29979251e-01,  8.50451044e-01],
       [ 6.25000000e-01,  5.89732278e-01,  8.91961163e-01],
       [ 6.25000000e-01,  7.64874801e-01,  2.21451546e-01],
       [ 6.25000000e-01,  6.35764791e-02,  5.11441616e-01],
       [ 2.50000000e-01,  6.11453234e-01,  9.64471958e-01],
       [ 8.75000000e-01,  7.35548236e-01, -1.44577068e-04],
       [ 0.00000000e+00,  9.44818799e-01,  5.51554385e-01],
       [ 6.25000000e-01,  2.40772748e-01,  3.15614201e-01],
       [ 8.75000000e-01,  6.82636329e-01,  5.88644857e-01],
       [ 5.00000000e-01,  5.36582664e-01,  7.54550828e-01],
       [ 1.25000000e-01,  1.72318245e-01,  6.43682419e-02],
       [ 3.75000000e-01,  7.97540340e-01,  3.20376945e-01],
       [ 5.00000000e-01,  1.76255515e-01,  4.24388139e-02],
       [ 1.25000000e-01,  1.92360146e-01,  4.05225970e-01],
       [ 6.25000000e-01,  9.09540501e-01,  1.61958776e-01],
       [ 6.25000000e-01,  8.84395963e-01,  6.85652953e-01],
       [ 0.00000000e+00,  5.02975363e-01,  2.26551824e-01],
       [ 0.00000000e+00,  6.97649121e-02,  1.78500865e-01],
       [ 6.25000000e-01,  7.46719446e-01,  4.00339085e-01],
       [ 5.00000000e-01,  4.92737858e-03,  4.74102354e-01],
       [ 6.25000000e-01,  8.15559719e-01,  6.76476839e-01],
       [ 3.75000000e-01,  5.71948591e-01,  4.87852799e-01],
       [ 3.75000000e-01,  9.52639955e-02,  2.26756934e-01],
       [ 7.50000000e-01,  7.68664008e-01,  5.13018421e-01],
       [ 1.00000000e+00,  9.44419935e-01,  6.82304752e-02],
       [ 7.50000000e-01,  9.55811728e-01,  4.45536879e-01],
       [ 0.00000000e+00,  1.51386958e-03,  1.10836156e-01],
       [ 6.25000000e-01,  4.57645898e-01,  7.26548789e-01],
       [ 0.00000000e+00,  1.97596745e-01,  9.88628457e-02],
       [ 5.00000000e-01,  7.26163856e-02,  1.49152625e-01],
       [ 8.75000000e-01,  8.38674684e-01,  7.78926022e-01],
       [ 1.00000000e+00,  4.38115671e-01,  8.46346413e-01],
       [ 5.00000000e-01,  8.32857920e-01,  1.13995108e-01],
       [ 6.25000000e-01,  4.19844483e-02,  8.59338016e-01],
       [ 6.25000000e-01,  5.51806974e-01,  3.91985916e-01],
       [ 1.25000000e-01,  3.90201648e-01,  9.28989639e-02],
       [ 1.25000000e-01,  1.58018573e-01,  9.53081908e-01],
       [ 5.00000000e-01,  7.27021011e-01,  7.82426847e-01],
       [ 2.50000000e-01,  4.66167080e-01,  6.73313626e-01],
       [ 5.00000000e-01,  7.86586692e-01,  9.73602142e-01],
       [ 6.25000000e-01,  8.58064906e-01,  9.69064579e-01],
       [ 1.00000000e+00,  9.95416088e-01,  3.72085484e-01],
       [ 2.50000000e-01,  7.75890897e-02,  9.58611634e-01],
       [ 5.00000000e-01,  3.14524284e-01,  6.76171799e-01],
       [ 8.75000000e-01,  3.13444532e-01,  3.86800782e-01],
       [ 1.00000000e+00,  6.88936565e-02,  6.00992298e-01],
       [ 6.25000000e-01,  7.40033440e-01,  6.68815570e-01],
       [ 1.25000000e-01,  9.58181745e-01,  5.24458991e-01],
       [ 1.00000000e+00,  7.29630749e-01,  3.34325054e-01],
       [ 7.50000000e-01,  6.06454342e-03,  2.54721025e-01],
       [ 1.00000000e+00,  1.15348200e-01,  8.80423859e-01],
       [ 8.75000000e-01,  1.62303338e-01,  1.72395884e-02],
       [ 5.00000000e-01,  4.61228622e-01,  3.42456469e-01],
       [ 1.25000000e-01,  2.66616305e-01,  3.23732230e-01],
       [ 5.00000000e-01,  3.96646925e-01,  6.08017138e-01],
       [ 0.00000000e+00,  9.96846357e-01,  2.85504647e-01],
       [ 7.50000000e-01,  3.83419955e-01,  8.84805516e-01],
       [ 2.50000000e-01,  1.52024536e-01,  6.29955700e-01],
       [ 0.00000000e+00,  5.90329566e-01,  6.29814907e-02],
       [ 2.50000000e-01,  5.46886646e-01,  7.41496758e-02],
       [ 7.50000000e-01,  9.92514252e-01,  6.34923382e-01],
       [ 8.75000000e-01,  4.50844060e-01,  6.14567672e-01],
       [ 0.00000000e+00,  9.97126367e-01,  7.34014300e-01],
       [ 6.25000000e-01,  3.34760581e-01,  7.61496696e-01],
       [ 1.00000000e+00,  5.52549304e-01,  6.18178991e-01],
       [ 1.00000000e+00,  5.86670293e-01,  6.48227141e-01],
       [ 5.00000000e-01,  6.11324309e-01,  1.07962556e-01],
       [ 1.00000000e+00,  3.02710461e-01,  4.85850207e-01],
       [ 8.75000000e-01,  2.38934550e-01,  4.48730761e-01],
       [ 7.50000000e-01,  8.89534860e-01,  3.18816588e-01],
       [ 3.75000000e-01,  5.17545980e-01,  4.70943873e-01],
       [ 5.00000000e-01,  7.95063556e-01,  2.76286480e-01],
       [ 1.25000000e-01,  6.18924881e-01,  1.67344101e-01],
       [ 1.25000000e-01,  2.80042707e-01,  2.16462391e-01],
       [ 6.25000000e-01,  5.75193892e-01,  9.75474576e-02],
       [ 6.25000000e-01,  8.92043875e-01,  2.34615461e-01],
       [ 2.50000000e-01,  7.91587599e-01,  6.61449448e-01],
       [ 1.25000000e-01,  4.47406378e-01,  8.78632062e-01],
       [ 0.00000000e+00,  9.57566326e-01,  3.57501904e-01],
       [ 3.75000000e-01,  6.81443766e-01,  1.70888383e-01],
       [ 8.75000000e-01,  8.40935920e-01,  7.56382571e-01],
       [ 5.00000000e-01,  5.56059507e-01,  6.53504875e-01],
       [ 0.00000000e+00,  1.29822123e-01,  1.61039747e-01],
       [ 0.00000000e+00,  3.32912310e-01,  8.99308447e-01],
       [ 1.25000000e-01,  2.08912995e-01,  7.64060835e-01],
       [ 5.00000000e-01,  6.56942850e-01,  8.82355473e-01],
       [ 7.50000000e-01,  5.54528515e-01,  6.15752679e-01],
       [ 0.00000000e+00,  5.09400496e-01,  9.45130297e-01],
       [ 6.25000000e-01,  3.17147116e-02,  5.68091624e-01],
       [ 2.50000000e-01,  7.59041921e-01,  7.09665319e-01],
       [ 1.00000000e+00,  5.48503253e-01,  3.44451652e-01],
       [ 0.00000000e+00,  9.01757620e-01,  5.40120903e-01],
       [ 5.00000000e-01,  7.98870893e-01,  2.55993932e-01],
       [ 7.50000000e-01,  1.17433170e-01,  8.27492640e-01],
       [ 2.50000000e-01,  1.89901493e-01,  7.04904942e-01],
       [ 7.50000000e-01,  6.32768276e-01,  5.26621060e-01],
       [ 8.75000000e-01,  7.51122056e-01,  1.85499621e-01],
       [ 0.00000000e+00,  1.38589070e-01,  5.00630555e-01],
       [ 6.25000000e-01,  7.09922242e-01,  3.93341285e-01],
       [ 7.50000000e-01,  1.71111581e-01,  8.90604897e-01],
       [ 7.50000000e-01,  5.85544207e-02,  7.21091625e-01],
       [ 0.00000000e+00,  6.20909128e-01,  1.72075970e-01],
       [ 7.50000000e-01,  2.69578574e-01,  3.31153186e-01],
       [ 7.50000000e-01,  2.91841421e-01,  1.11967803e-01],
       [ 8.75000000e-01,  9.53305735e-01,  4.43520802e-01],
       [ 5.00000000e-01,  6.08626941e-01,  9.98397117e-01],
       [ 1.25000000e-01,  3.23063597e-01,  8.25538163e-02],
       [ 0.00000000e+00,  8.55768417e-01,  3.55059221e-01],
       [ 3.75000000e-01,  2.71287847e-01,  4.58016685e-01],
       [ 1.25000000e-01,  2.85120163e-01,  7.34506566e-01],
       [ 0.00000000e+00,  9.63918938e-01,  3.29119792e-01]])

In [98]:
model.fit(xtrain_scaled,ytrain)

LinearRegression()

In [99]:
train_score=model.score(xtrain_scaled,ytrain)
train_score

0.9902808869604561

In [100]:
test_score=model.score(xtest_scaled,ytest)
test_score

0.9902822563064015

In [101]:
model.coef_

array([-1.52733656e+02,  2.53397830e+02,  1.79404745e+05])

* array([-1.90917070e+01,  2.55230384e-04,  1.79990677e+00])--->without Standard Scaler
* array([-4.91513611e+01,  7.40118263e+01,  5.19891719e+04])---->with standard Scaler
* array([-7.63668279e+01,  1.27686274e+02,  9.25658986e+04])---->Robust Scaler
* array([-1.52733656e+02,  2.53397830e+02,  1.79404745e+05])----->Minmax Scaler

**using Label encoder**

In [102]:
from sklearn.preprocessing import LabelEncoder

In [103]:
df=pd.DataFrame({'color':['Red','Blue','Green','Red','Blue'],'level':['low','high','medium','low','high'],'size':['small','large','medium','large','small'],'city':['newyork','washington','newyork','delhi','washington'],'purchased':['yes','no','no','yes','yes']})

In [104]:
label_encoder=LabelEncoder()

In [105]:
label_encoder.fit(df['color'])

LabelEncoder()

In [106]:
label_encoder.fit_transform(['Red'])

array([0])

In [107]:
label_encoder.transform(['Red'])

array([0])

In [108]:
'''label_encoder.transform(['Redd'])
ValueError:(y contains previously unseen labels: 'Redd')'''

"label_encoder.transform(['Redd'])\nValueError:(y contains previously unseen labels: 'Redd')"

In [109]:
'''label_encoder.transform([['Red','Red']])
ValueError: y should be a 1d array, got an array of shape (1, 2) instead.'''

"label_encoder.transform([['Red','Red']])\nValueError: y should be a 1d array, got an array of shape (1, 2) instead."

**Using One hot encoder**

In [110]:
from sklearn.preprocessing import OneHotEncoder

In [111]:
one_hot_encoder=OneHotEncoder()

In [112]:
one_hot_encoder.fit_transform(df[['size']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (5, 3)>

In [113]:
'''one_hot_encoder.fit_transform(df['size'])
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.'''

"one_hot_encoder.fit_transform(df['size'])\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. \nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead."

In [114]:
one_hot_encoder.fit(df[['size']])   #it accepts 2D

OneHotEncoder()

In [115]:
res=one_hot_encoder.fit_transform(df[['color','city']])
res

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (5, 6)>

In [116]:
res_cols=one_hot_encoder.get_feature_names_out()

In [117]:
res=res.toarray()

In [118]:
pd.DataFrame(res,columns=res_cols)

,color_Blue,color_Green,color_Red,city_delhi,city_newyork,city_washington
0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0

In [119]:
one_hot_encoder=OneHotEncoder(sparse_output=False,dtype='int')

In [120]:
res=one_hot_encoder.fit_transform(df[['color','city']])

In [121]:
one_hot_encoder.fit(df[['color','city']])

OneHotEncoder(dtype='int', sparse_output=False)

In [122]:
'''one_hot_encoder.transform(df[['color']])
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- city'''

"one_hot_encoder.transform(df[['color']])\nValueError: The feature names should match those that were passed during fit.\nFeature names seen at fit time, yet now missing:\n- city"

In [123]:
one_hot_encoder.fit_transform(df[['color','city']])

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 1]])

In [124]:
'''one_hot_encoder.transform([['Red']])
ValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.'''

"one_hot_encoder.transform([['Red']])\nValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input."

In [125]:
one_hot_encoder.transform([['Red','newyork']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0, 0, 1, 0, 1, 0]])

In [126]:
'''one_hot_encoder.transform([['Redd','newyork']])
ValueError: Found unknown categories ['Redd'] in column 0 during transform'''

"one_hot_encoder.transform([['Redd','newyork']])\nValueError: Found unknown categories ['Redd'] in column 0 during transform"

In [127]:
'''one_hot_encoder.transform([['Red','Red']])
ValueError: Found unknown categories ['Red'] in column 1 during transform'''

"one_hot_encoder.transform([['Red','Red']])\nValueError: Found unknown categories ['Red'] in column 1 during transform"

In [128]:
one_hot_encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [129]:
one_hot_encoder.fit_transform(df[['color']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [130]:
one_hot_encoder.transform([['Red'],['Redd']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.],
       [0., 0., 0.]])

In [131]:
one_hot_encoder.transform([['Redd']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0.]])

**Ordinal encoder**

In [132]:
from sklearn.preprocessing import  OrdinalEncoder

In [133]:
ordinal_encoder=OrdinalEncoder()

In [134]:
df

   color   level    size        city purchased
0    Red     low   small     newyork       yes
1   Blue    high   large  washington        no
2  Green  medium  medium     newyork        no
3    Red     low   large       delhi       yes
4   Blue    high   small  washington       yes

In [135]:
OrdinalEncoder(categories=[['Red','Blue','Green'],['low','high','medium'],['small','large','medium'],['newyork','washington','delhi'],['yes','no']])

OrdinalEncoder(categories=[['Red', 'Blue', 'Green'], ['low', 'high', 'medium'],
                           ['small', 'large', 'medium'],
                           ['newyork', 'washington', 'delhi'], ['yes', 'no']])

In [136]:
'''ordinal_encoder=OrdinalEncoder(categories=['Red','Blue','Green'])
ordinal_encoder.fit_transform(df['color'])
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.'''

"ordinal_encoder=OrdinalEncoder(categories=['Red','Blue','Green'])\nordinal_encoder.fit_transform(df['color'])\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead."

In [137]:
'''ordinal_encoder=OrdinalEncoder(categories=[['low','high','medium'],['Red','Blue','Green'],['newyork','washington','delhi'],['yes','no'],['small','large','medium']])
ordinal_encoder.fit_transform(df)
ValueError: Found unknown categories ['Blue', 'Red', 'Green'] in column 0 during fit'''

"ordinal_encoder=OrdinalEncoder(categories=[['low','high','medium'],['Red','Blue','Green'],['newyork','washington','delhi'],['yes','no'],['small','large','medium']])\nordinal_encoder.fit_transform(df)\nValueError: Found unknown categories ['Blue', 'Red', 'Green'] in column 0 during fit"

In [138]:
ordinal_encoder.fit_transform(df)

array([[2., 1., 2., 1., 1.],
       [0., 0., 0., 2., 0.],
       [1., 2., 1., 1., 0.],
       [2., 1., 0., 0., 1.],
       [0., 0., 2., 2., 1.]])

In [139]:
'''ordinal_encoder.transform([['Red']])
ValueError: X has 1 features, but OrdinalEncoder is expecting 5 features as input'''

"ordinal_encoder.transform([['Red']])\nValueError: X has 1 features, but OrdinalEncoder is expecting 5 features as input"

**how to handle unknown values**

In [140]:
'''ordinal_encoder=OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value")
values=ordinal_encoder.fit_transform(df[['color']])
ordinal_encoder.transform([['orange']])
TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.'''

'ordinal_encoder=OrdinalEncoder(categories=[[\'Blue\',\'Green\',\'Red\']],handle_unknown="use_encoded_value")\nvalues=ordinal_encoder.fit_transform(df[[\'color\']])\nordinal_encoder.transform([[\'orange\']])\nTypeError: unknown_value should be an integer or np.nan when handle_unknown is \'use_encoded_value\', got None.'

In [141]:
'''ordinal_encoder=OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value",unknown_value=0)
values=ordinal_encoder.fit_transform(df[['color']])
ordinal_encoder.transform([['orange']])
ValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.'''

'ordinal_encoder=OrdinalEncoder(categories=[[\'Blue\',\'Green\',\'Red\']],handle_unknown="use_encoded_value",unknown_value=0)\nvalues=ordinal_encoder.fit_transform(df[[\'color\']])\nordinal_encoder.transform([[\'orange\']])\nValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.'

In [142]:
ordinal_encoder=OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value",unknown_value=-1)
values=ordinal_encoder.fit_transform(df[['color']])
ordinal_encoder.transform([['orange']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1.]])